services:
  frontend:
    build:
      context: ./game-host
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://backend:4000

  backend:
    build:
      context: ./backend
    ports:
      - "4000:4000"
    volumes:
      - ./backend/uploads:/app/uploads
    environment:
      - NODE_ENV=production
